apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-notes
  namespace: code-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-notes
  template:
    metadata:
      labels:
        app: flask-notes
    spec:
      containers:
        - name: flask-notes
          image: ayushjsrtia/code-analyzer-backend:latest
          env:
            - name: MYSQL_HOST
              value: "10.32.0.3"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "NOTES"
          ports:
            - containerPort: 5000
