apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-notes-hpa
  namespace: code-analyzer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-notes
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
