apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: code-analyzer
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  hostPath: 
    path: /data/mysql